import { format } from "date-fns";

export function formatDuration(minutes: number): string {
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  if (hours === 0) return `${mins}m`;
  if (mins === 0) return `${hours}h`;
  return `${hours}h ${mins}m`;
}

export function formatTime(time: string): string {
  const [hours, minutes] = time.split(":");
  const hour = parseInt(hours);
  const ampm = hour >= 12 ? "PM" : "AM";
  const hour12 = hour % 12 || 12;
  return `${hour12}:${minutes} ${ampm}`;
}

export function exportToCSV(data: any[], filename: string) {
  // Define headers
  const headers = [
    "Date",
    "Member",
    "Department",
    "Activity Type",
    "Activity Subtype",
    "Start Time",
    "End Time",
    "Duration",
    "Status",
    "Notes",
  ];

  // Map data to CSV rows
  const rows = data.map((entry) => [
    format(new Date(entry.entry_date), "MMM dd, yyyy"),
    entry.profiles?.full_name || "N/A",
    entry.departments?.name || "N/A",
    entry.activity_type,
    entry.activity_subtype || "",
    entry.start_time,
    entry.end_time,
    formatDuration(entry.duration_minutes),
    entry.status,
    entry.notes || "",
  ]);

  // Combine headers and rows
  const csvContent = [headers, ...rows]
    .map((row) => row.map((cell) => `"${cell}"`).join(","))
    .join("\n");

  // Create blob and download
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}_${format(new Date(), "yyyy-MM-dd")}.csv`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportToCSVWithMetadata(
  data: any[],
  filename: string,
  metadata: {
    reportPeriod: string;
    generatedBy: string;
    totalHours: number;
    totalEntries: number;
  }
) {
  // Create metadata header
  const metadataRows = [
    ["Timesheet Report"],
    [""],
    ["Report Period:", metadata.reportPeriod],
    ["Generated:", format(new Date(), "PPP p")],
    ["Generated By:", metadata.generatedBy],
    ["Total Entries:", metadata.totalEntries.toString()],
    ["Total Hours:", (metadata.totalHours / 60).toFixed(1)],
    [""],
  ];

  // Define data headers
  const headers = [
    "Date",
    "Member",
    "Department",
    "Activity Type",
    "Activity Subtype",
    "Start Time",
    "End Time",
    "Duration",
    "Status",
    "Notes",
  ];

  // Map data to CSV rows
  const dataRows = data.map((entry) => [
    format(new Date(entry.entry_date), "MMM dd, yyyy"),
    entry.profiles?.full_name || "N/A",
    entry.departments?.name || "N/A",
    entry.activity_type,
    entry.activity_subtype || "",
    entry.start_time,
    entry.end_time,
    formatDuration(entry.duration_minutes),
    entry.status,
    entry.notes || "",
  ]);

  // Combine all rows
  const csvContent = [...metadataRows, headers, ...dataRows]
    .map((row) => row.map((cell) => `"${cell}"`).join(","))
    .join("\n");

  // Create blob and download
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}_${format(new Date(), "yyyy-MM-dd")}.csv`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportMemberReportCSV(
  report: any,
  reportPeriod: string,
  generatedBy: string,
  period: string
) {
  const metadataRows = [
    ["Faculty Timesheet Report"],
    [""],
    ["Report Type:", "Faculty Report"],
    ["Period:", `${reportPeriod} (${period})`],
    ["Faculty:", report.facultyName],
    ["Department:", report.department],
    ["Generated:", format(new Date(), "PPP p")],
    ["Generated By:", generatedBy],
    [""],
    ["Summary Metrics:"],
    ["Total Hours Logged:", `${report.totalHours.toFixed(1)} hours`],
    ["Expected Hours:", `${report.expectedHours.toFixed(1)} hours`],
    ["Completion Rate:", `${report.completionRate.toFixed(1)}%`],
    ["Status:", report.completionRate >= 100 ? "Exceeded Target" : report.completionRate >= 70 ? "On Track" : "Behind Schedule"],
    ["Average Daily Hours:", `${report.averageDailyHours.toFixed(1)} hours`],
    [""],
    ["Activity Breakdown:"],
    ...report.activityBreakdown.map((activity: any) => [
      `${activity.activityType}:`,
      `${activity.hours.toFixed(1)} hours (${activity.percentage.toFixed(1)}%)`,
    ]),
    [""],
    ["Daily Breakdown:"],
  ];

  const headers = [
    "Date",
    "Activity Type",
    "Activity Subtype",
    "Start Time",
    "End Time",
    "Duration",
    "Status",
    "Notes",
  ];

  const dataRows = report.entries.map((entry: any) => [
    format(new Date(entry.entry_date), "MMM dd, yyyy"),
    entry.activity_type,
    entry.activity_subtype || "",
    entry.start_time,
    entry.end_time,
    formatDuration(entry.duration_minutes),
    entry.status,
    entry.notes || "",
  ]);

  const csvContent = [...metadataRows, headers, ...dataRows]
    .map((row) => row.map((cell) => `"${cell}"`).join(","))
    .join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", `faculty_report_${report.facultyName.replace(/\s+/g, "_")}_${format(new Date(), "yyyy-MM-dd")}.csv`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportDepartmentReportCSV(
  report: any,
  reportPeriod: string,
  generatedBy: string,
  period: string
) {
  const metadataRows = [
    ["Department Timesheet Report"],
    [""],
    ["Report Type:", "Department Report"],
    ["Period:", `${reportPeriod} (${period})`],
    ["Department:", report.departmentName],
    ["Total Members:", report.totalFaculty.toString()],
    ["Generated:", format(new Date(), "PPP p")],
    ["Generated By:", generatedBy],
    [""],
    ["Summary Metrics:"],
    ["Total Hours Logged:", `${report.totalHours.toFixed(1)} hours`],
    ["Expected Hours:", `${report.expectedHours.toFixed(1)} hours`],
    ["Completion Rate:", `${report.completionRate.toFixed(1)}%`],
    ["Average Daily Hours:", `${report.averageDailyHours.toFixed(1)} hours`],
    [""],
    ["Activity Breakdown:"],
    ...report.activityBreakdown.map((activity: any) => [
      `${activity.activityType}:`,
      `${activity.hours.toFixed(1)} hours (${activity.percentage.toFixed(1)}%)`,
    ]),
    [""],
    ["Member Breakdown:"],
  ];

  const headers = [
    "Member Name",
    "Hours Logged",
    "Completion Rate",
    "Total Entries",
    "Status",
  ];

  const dataRows = report.facultyBreakdown.map((faculty: any) => [
    faculty.facultyName,
    `${faculty.totalHours.toFixed(1)} hours`,
    `${faculty.completionRate.toFixed(1)}%`,
    faculty.entryCount.toString(),
    faculty.completionRate >= 100 ? "Exceeded" : faculty.completionRate >= 70 ? "On Track" : "Behind",
  ]);

  const csvContent = [...metadataRows, headers, ...dataRows]
    .map((row) => row.map((cell) => `"${cell}"`).join(","))
    .join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", `department_report_${report.departmentName.replace(/\s+/g, "_")}_${format(new Date(), "yyyy-MM-dd")}.csv`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

