import { format } from "date-fns";

export function formatDuration(minutes: number): string {
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  if (hours === 0) return `${mins}m`;
  if (mins === 0) return `${hours}h`;
  return `${hours}h ${mins}m`;
}

export function formatTime(time: string): string {
  const [hours, minutes] = time.split(":");
  const hour = parseInt(hours);
  const ampm = hour >= 12 ? "PM" : "AM";
  const hour12 = hour % 12 || 12;
  return `${hour12}:${minutes} ${ampm}`;
}

export function exportToCSV(data: any[], filename: string) {
  // Define headers
  const headers = [
    "Date",
    "Faculty",
    "Department",
    "Activity Type",
    "Activity Subtype",
    "Start Time",
    "End Time",
    "Duration",
    "Status",
    "Notes",
  ];

  // Map data to CSV rows
  const rows = data.map((entry) => [
    format(new Date(entry.entry_date), "MMM dd, yyyy"),
    entry.profiles?.full_name || "N/A",
    entry.departments?.name || "N/A",
    entry.activity_type,
    entry.activity_subtype || "",
    entry.start_time,
    entry.end_time,
    formatDuration(entry.duration_minutes),
    entry.status,
    entry.notes || "",
  ]);

  // Combine headers and rows
  const csvContent = [headers, ...rows]
    .map((row) => row.map((cell) => `"${cell}"`).join(","))
    .join("\n");

  // Create blob and download
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}_${format(new Date(), "yyyy-MM-dd")}.csv`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportToCSVWithMetadata(
  data: any[],
  filename: string,
  metadata: {
    reportPeriod: string;
    generatedBy: string;
    totalHours: number;
    totalEntries: number;
  }
) {
  // Create metadata header
  const metadataRows = [
    ["Timesheet Report"],
    [""],
    ["Report Period:", metadata.reportPeriod],
    ["Generated:", format(new Date(), "PPP p")],
    ["Generated By:", metadata.generatedBy],
    ["Total Entries:", metadata.totalEntries.toString()],
    ["Total Hours:", (metadata.totalHours / 60).toFixed(1)],
    [""],
  ];

  // Define data headers
  const headers = [
    "Date",
    "Faculty",
    "Department",
    "Activity Type",
    "Activity Subtype",
    "Start Time",
    "End Time",
    "Duration",
    "Status",
    "Notes",
  ];

  // Map data to CSV rows
  const dataRows = data.map((entry) => [
    format(new Date(entry.entry_date), "MMM dd, yyyy"),
    entry.profiles?.full_name || "N/A",
    entry.departments?.name || "N/A",
    entry.activity_type,
    entry.activity_subtype || "",
    entry.start_time,
    entry.end_time,
    formatDuration(entry.duration_minutes),
    entry.status,
    entry.notes || "",
  ]);

  // Combine all rows
  const csvContent = [...metadataRows, headers, ...dataRows]
    .map((row) => row.map((cell) => `"${cell}"`).join(","))
    .join("\n");

  // Create blob and download
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}_${format(new Date(), "yyyy-MM-dd")}.csv`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
