import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { formatDuration } from "./exportUtils";

interface TimesheetEntry {
  entry_date: string;
  profiles?: { full_name: string };
  departments?: { name: string };
  activity_type: string;
  activity_subtype?: string | null;
  duration_minutes: number;
  status: string;
}

export function exportToPDF(
  entries: TimesheetEntry[],
  filename: string,
  metadata: {
    reportPeriod: string;
    generatedBy: string;
    totalHours: number;
    approvedHours: number;
    pendingCount: number;
  }
) {
  const doc = new jsPDF();

  // Add header
  doc.setFontSize(20);
  doc.setTextColor(41, 128, 185);
  doc.text("Timesheet Report", 14, 22);

  // Add metadata
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(`Report Period: ${metadata.reportPeriod}`, 14, 32);
  doc.text(`Generated: ${format(new Date(), "PPP")}`, 14, 38);
  doc.text(`Generated By: ${metadata.generatedBy}`, 14, 44);

  // Add summary section
  doc.setFontSize(12);
  doc.setTextColor(41, 128, 185);
  doc.text("Summary", 14, 54);

  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Entries: ${entries.length}`, 14, 62);
  doc.text(`Total Hours: ${(metadata.totalHours / 60).toFixed(1)}`, 14, 68);
  doc.text(`Approved Hours: ${(metadata.approvedHours / 60).toFixed(1)}`, 14, 74);
  doc.text(`Pending Approvals: ${metadata.pendingCount}`, 14, 80);

  // Add table
  autoTable(doc, {
    startY: 90,
    head: [["Date", "Member", "Department", "Activity", "Duration", "Status"]],
    body: entries.map((entry) => [
      format(new Date(entry.entry_date), "MMM dd, yyyy"),
      entry.profiles?.full_name || "N/A",
      entry.departments?.name || "N/A",
      `${entry.activity_type}${entry.activity_subtype ? ` - ${entry.activity_subtype}` : ""}`,
      formatDuration(entry.duration_minutes),
      entry.status,
    ]),
    theme: "striped",
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
  });

  // Add footer with page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }

  // Save PDF
  doc.save(`${filename}_${format(new Date(), "yyyy-MM-dd")}.pdf`);
}

export function exportMemberReportPDF(
  report: any,
  reportPeriod: string,
  generatedBy: string,
  period: string
) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(41, 128, 185);
  doc.text("Member Timesheet Report", 14, 22);

  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(`Member: ${report.facultyName}`, 14, 32);
  doc.text(`Department: ${report.department}`, 14, 38);
  doc.text(`Period: ${reportPeriod} (${period})`, 14, 44);
  doc.text(`Generated: ${format(new Date(), "PPP")}`, 14, 50);
  doc.text(`Generated By: ${generatedBy}`, 14, 56);

  // Summary
  doc.setFontSize(12);
  doc.setTextColor(41, 128, 185);
  doc.text("Summary Metrics", 14, 66);

  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Hours Logged: ${report.totalHours.toFixed(1)} hours`, 14, 74);
  doc.text(`Expected Hours: ${report.expectedHours.toFixed(1)} hours`, 14, 80);
  doc.text(`Completion Rate: ${report.completionRate.toFixed(1)}%`, 14, 86);
  doc.text(`Average Daily Hours: ${report.averageDailyHours.toFixed(1)} hours`, 14, 92);
  const status = report.completionRate >= 100 ? "Exceeded Target" : report.completionRate >= 70 ? "On Track" : "Behind Schedule";
  doc.text(`Status: ${status}`, 14, 98);

  // Activity Breakdown
  doc.setFontSize(12);
  doc.setTextColor(41, 128, 185);
  doc.text("Activity Breakdown", 14, 108);

  let yPos = 116;
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  report.activityBreakdown.forEach((activity: any) => {
    doc.text(
      `${activity.activityType}: ${activity.hours.toFixed(1)}h (${activity.percentage.toFixed(1)}%)`,
      14,
      yPos
    );
    yPos += 6;
  });

  // Detailed Table
  autoTable(doc, {
    startY: yPos + 10,
    head: [["Date", "Activity", "Time", "Duration", "Status"]],
    body: report.entries.map((entry: any) => [
      format(new Date(entry.entry_date), "MMM dd, yyyy"),
      `${entry.activity_type}${entry.activity_subtype ? ` - ${entry.activity_subtype}` : ""}`,
      `${entry.start_time} - ${entry.end_time}`,
      formatDuration(entry.duration_minutes),
      entry.status,
    ]),
    theme: "striped",
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }

  doc.save(`faculty_report_${report.facultyName.replace(/\s+/g, "_")}_${format(new Date(), "yyyy-MM-dd")}.pdf`);
}

export function exportDepartmentReportPDF(
  report: any,
  reportPeriod: string,
  generatedBy: string,
  period: string
) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(41, 128, 185);
  doc.text("Department Timesheet Report", 14, 22);

  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(`Department: ${report.departmentName}`, 14, 32);
  doc.text(`Total Faculty: ${report.totalFaculty}`, 14, 38);
  doc.text(`Period: ${reportPeriod} (${period})`, 14, 44);
  doc.text(`Generated: ${format(new Date(), "PPP")}`, 14, 50);
  doc.text(`Generated By: ${generatedBy}`, 14, 56);

  // Summary
  doc.setFontSize(12);
  doc.setTextColor(41, 128, 185);
  doc.text("Summary Metrics", 14, 66);

  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Hours Logged: ${report.totalHours.toFixed(1)} hours`, 14, 74);
  doc.text(`Expected Hours: ${report.expectedHours.toFixed(1)} hours`, 14, 80);
  doc.text(`Completion Rate: ${report.completionRate.toFixed(1)}%`, 14, 86);
  doc.text(`Average Daily Hours: ${report.averageDailyHours.toFixed(1)} hours`, 14, 92);

  // Activity Breakdown
  doc.setFontSize(12);
  doc.setTextColor(41, 128, 185);
  doc.text("Activity Breakdown", 14, 102);

  let yPos = 110;
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  report.activityBreakdown.forEach((activity: any) => {
    doc.text(
      `${activity.activityType}: ${activity.hours.toFixed(1)}h (${activity.percentage.toFixed(1)}%)`,
      14,
      yPos
    );
    yPos += 6;
  });

  // Faculty Breakdown Table
  autoTable(doc, {
    startY: yPos + 10,
    head: [["Faculty Name", "Hours", "Completion", "Entries", "Status"]],
    body: report.facultyBreakdown.map((faculty: any) => [
      faculty.facultyName,
      `${faculty.totalHours.toFixed(1)}h`,
      `${faculty.completionRate.toFixed(1)}%`,
      faculty.entryCount.toString(),
      faculty.completionRate >= 100 ? "Exceeded" : faculty.completionRate >= 70 ? "On Track" : "Behind",
    ]),
    theme: "striped",
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }

  doc.save(`department_report_${report.departmentName.replace(/\s+/g, "_")}_${format(new Date(), "yyyy-MM-dd")}.pdf`);
}

