import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { formatDuration } from "./exportUtils";

interface TimesheetEntry {
  entry_date: string;
  profiles?: { full_name: string };
  departments?: { name: string };
  activity_type: string;
  activity_subtype?: string | null;
  duration_minutes: number;
  status: string;
}

export function exportToPDF(
  entries: TimesheetEntry[],
  filename: string,
  metadata: {
    reportPeriod: string;
    generatedBy: string;
    totalHours: number;
    approvedHours: number;
    pendingCount: number;
  }
) {
  const doc = new jsPDF();

  // Add header
  doc.setFontSize(20);
  doc.setTextColor(41, 128, 185);
  doc.text("Timesheet Report", 14, 22);

  // Add metadata
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(`Report Period: ${metadata.reportPeriod}`, 14, 32);
  doc.text(`Generated: ${format(new Date(), "PPP")}`, 14, 38);
  doc.text(`Generated By: ${metadata.generatedBy}`, 14, 44);

  // Add summary section
  doc.setFontSize(12);
  doc.setTextColor(41, 128, 185);
  doc.text("Summary", 14, 54);

  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Entries: ${entries.length}`, 14, 62);
  doc.text(`Total Hours: ${(metadata.totalHours / 60).toFixed(1)}`, 14, 68);
  doc.text(`Approved Hours: ${(metadata.approvedHours / 60).toFixed(1)}`, 14, 74);
  doc.text(`Pending Approvals: ${metadata.pendingCount}`, 14, 80);

  // Add table
  autoTable(doc, {
    startY: 90,
    head: [["Date", "Faculty", "Department", "Activity", "Duration", "Status"]],
    body: entries.map((entry) => [
      format(new Date(entry.entry_date), "MMM dd, yyyy"),
      entry.profiles?.full_name || "N/A",
      entry.departments?.name || "N/A",
      `${entry.activity_type}${entry.activity_subtype ? ` - ${entry.activity_subtype}` : ""}`,
      formatDuration(entry.duration_minutes),
      entry.status,
    ]),
    theme: "striped",
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
  });

  // Add footer with page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }

  // Save PDF
  doc.save(`${filename}_${format(new Date(), "yyyy-MM-dd")}.pdf`);
}
