project_id = "txufiwzngzdspczttcqx"

[functions.seed-test-users]
verify_jwt = false

[functions.seed-super-admins]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.seed-mab-faculty]
verify_jwt = false
